import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PSP A1 Programs</title>
        <meta name="description" content="Generated by create next app" />
        <link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
/>
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/icon?family=Material+Icons"
/>

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <p className={styles.title}>
        PSP A1 Programs
       </p >
        <div className={styles.grid}>
          <a href="/programs/bmi" className={styles.card}>
            <h2>Program 1 &rarr;</h2>
            <p>BMI Calculator <br/> Given the weight and height of a person. Find the BMI(Body Mass Index) </p>
          </a>

          <a href="/programs/discountcalculator" className={styles.card}>
            <h2>Program 2 &rarr;</h2>
            <p>Discount Calculator <br/>Given the sale amount, calculate the discount based on the sale amount</p>
          </a>
    
          <a
            href="/programs/zipzapzoom"
            className={styles.card}
          >
            <h2>Program 3 &rarr;</h2>
            <p>Zip Zap Zoom <br/>Display a message based on a given number. </p>
          </a>

          <a
            href="/programs/perfectnumber"
            className={styles.card}
          >
            <h2>Program 4 &rarr;</h2>
            <p>Find Perfect Number <br/>Given an integer number, check if it a perfect number or not  </p>
          </a>

          
        </div>
      </main>

    </div>
  )
}
