import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PSP A1 Programs</title>
        <meta name="description" content="Generated by create next app" />
        <link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
/>
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/icon?family=Material+Icons"
/>

        <Script
   id="Adsense-id"
   async="true"
   strategy="beforeInteractive"
    src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6813609620822362"
    crossOrigin = "anonymous"
/>
        
        
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <p className={styles.title}>
        PSP A1 Programs
       </p >
        <div className={styles.grid}>
          <Link href="/programs/bmi">
          <a  className={styles.card}>
            <h2>Program 1 &rarr;</h2>
            <p>BMI Calculator <br/> Given the weight and height of a person. Find the BMI(Body Mass Index) </p>
          </a>
          </Link>
        <Link href="/programs/discountcalculator" >
          <a className={styles.card}>
            <h2>Program 2 &rarr;</h2>
            <p>Discount Calculator <br/>Given the sale amount, calculate the discount based on the sale amount</p>
          </a>
          </Link>
          <Link  href="/programs/zipzapzoom">
          <a className={styles.card}   >
            <h2>Program 3 &rarr;</h2>
            <p>Zip Zap Zoom <br/>Display a message based on a given number. </p>
          </a>
          </Link>
          <Link href="/programs/perfectnumber">
          <a
            
            className={styles.card}
          >
            <h2>Program 4 &rarr;</h2>
            <p>Find Perfect Number <br/>Given an integer number, check if it a perfect number or not  </p>
          </a>
          </Link>
          
        </div>
      </main>

    </div>
  )
}
